# Generated by Django 2.2.6 on 2019-10-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191028_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tr_date',
            field=models.DateTimeField(verbose_name='tr date published '),
        ),
    ]
