# Generated by Django 2.2.6 on 2019-10-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191028_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='memo',
            new_name='tr_memo',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tr_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
